server:
  port: 8001
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/Learn/boot-cloud/config/config-repo
  application:
    name: cloud-config-server
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
#springboot 1.5.X 以上默认开通了安全认证，访问/bus/refresh或者/refresh的时候需要验证
management:
  security:
     enabled: false