server:
  port: 8001
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/Learn/boot-cloud/config/config-repo
  application:
    name: cloud-config-server
  profiles:
    active: native
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/