spring:
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: @project.artifactId@
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 9001